package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.thickness.model.ConfigBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONFIG_BEAN".
*/
public class ConfigBeanDao extends AbstractDao<ConfigBean, Long> {

    public static final String TABLENAME = "CONFIG_BEAN";

    /**
     * Properties of entity ConfigBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PoleName = new Property(1, String.class, "poleName", false, "POLE_NAME");
        public final static Property PoleHeight = new Property(2, String.class, "poleHeight", false, "POLE_HEIGHT");
        public final static Property PoleBottomDiameter = new Property(3, int.class, "poleBottomDiameter", false, "POLE_BOTTOM_DIAMETER");
        public final static Property PoleTopDiameter = new Property(4, int.class, "poleTopDiameter", false, "POLE_TOP_DIAMETER");
        public final static Property RebarDiameter = new Property(5, int.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property HoopingDiameter = new Property(6, int.class, "hoopingDiameter", false, "HOOPING_DIAMETER");
        public final static Property PoleType = new Property(7, String.class, "poleType", false, "POLE_TYPE");
        public final static Property PoleStructure = new Property(8, int.class, "poleStructure", false, "POLE_STRUCTURE");
        public final static Property DesignThickness = new Property(9, String.class, "designThickness", false, "DESIGN_THICKNESS");
    }


    public ConfigBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ConfigBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONFIG_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"POLE_NAME\" TEXT," + // 1: poleName
                "\"POLE_HEIGHT\" TEXT," + // 2: poleHeight
                "\"POLE_BOTTOM_DIAMETER\" INTEGER NOT NULL ," + // 3: poleBottomDiameter
                "\"POLE_TOP_DIAMETER\" INTEGER NOT NULL ," + // 4: poleTopDiameter
                "\"REBAR_DIAMETER\" INTEGER NOT NULL ," + // 5: rebarDiameter
                "\"HOOPING_DIAMETER\" INTEGER NOT NULL ," + // 6: hoopingDiameter
                "\"POLE_TYPE\" TEXT," + // 7: poleType
                "\"POLE_STRUCTURE\" INTEGER NOT NULL ," + // 8: poleStructure
                "\"DESIGN_THICKNESS\" TEXT);"); // 9: designThickness
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONFIG_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ConfigBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poleName = entity.getPoleName();
        if (poleName != null) {
            stmt.bindString(2, poleName);
        }
 
        String poleHeight = entity.getPoleHeight();
        if (poleHeight != null) {
            stmt.bindString(3, poleHeight);
        }
        stmt.bindLong(4, entity.getPoleBottomDiameter());
        stmt.bindLong(5, entity.getPoleTopDiameter());
        stmt.bindLong(6, entity.getRebarDiameter());
        stmt.bindLong(7, entity.getHoopingDiameter());
 
        String poleType = entity.getPoleType();
        if (poleType != null) {
            stmt.bindString(8, poleType);
        }
        stmt.bindLong(9, entity.getPoleStructure());
 
        String designThickness = entity.getDesignThickness();
        if (designThickness != null) {
            stmt.bindString(10, designThickness);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ConfigBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poleName = entity.getPoleName();
        if (poleName != null) {
            stmt.bindString(2, poleName);
        }
 
        String poleHeight = entity.getPoleHeight();
        if (poleHeight != null) {
            stmt.bindString(3, poleHeight);
        }
        stmt.bindLong(4, entity.getPoleBottomDiameter());
        stmt.bindLong(5, entity.getPoleTopDiameter());
        stmt.bindLong(6, entity.getRebarDiameter());
        stmt.bindLong(7, entity.getHoopingDiameter());
 
        String poleType = entity.getPoleType();
        if (poleType != null) {
            stmt.bindString(8, poleType);
        }
        stmt.bindLong(9, entity.getPoleStructure());
 
        String designThickness = entity.getDesignThickness();
        if (designThickness != null) {
            stmt.bindString(10, designThickness);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ConfigBean readEntity(Cursor cursor, int offset) {
        ConfigBean entity = new ConfigBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // poleName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // poleHeight
            cursor.getInt(offset + 3), // poleBottomDiameter
            cursor.getInt(offset + 4), // poleTopDiameter
            cursor.getInt(offset + 5), // rebarDiameter
            cursor.getInt(offset + 6), // hoopingDiameter
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // poleType
            cursor.getInt(offset + 8), // poleStructure
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // designThickness
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ConfigBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPoleName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPoleHeight(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPoleBottomDiameter(cursor.getInt(offset + 3));
        entity.setPoleTopDiameter(cursor.getInt(offset + 4));
        entity.setRebarDiameter(cursor.getInt(offset + 5));
        entity.setHoopingDiameter(cursor.getInt(offset + 6));
        entity.setPoleType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPoleStructure(cursor.getInt(offset + 8));
        entity.setDesignThickness(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ConfigBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ConfigBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ConfigBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
