package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.corrosion.model.CurveMinMaxBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CURVE_MIN_MAX_BEAN".
*/
public class CurveMinMaxBeanDao extends AbstractDao<CurveMinMaxBean, Long> {

    public static final String TABLENAME = "CURVE_MIN_MAX_BEAN";

    /**
     * Properties of entity CurveMinMaxBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UniqueKey = new Property(1, String.class, "uniqueKey", false, "UNIQUE_KEY");
        public final static Property RebarDiameter = new Property(2, String.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property Thickness = new Property(3, double.class, "thickness", false, "THICKNESS");
        public final static Property SignalMin = new Property(4, double.class, "signalMin", false, "SIGNAL_MIN");
        public final static Property SignalMax = new Property(5, double.class, "signalMax", false, "SIGNAL_MAX");
    }


    public CurveMinMaxBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CurveMinMaxBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CURVE_MIN_MAX_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UNIQUE_KEY\" TEXT UNIQUE ," + // 1: uniqueKey
                "\"REBAR_DIAMETER\" TEXT," + // 2: rebarDiameter
                "\"THICKNESS\" REAL NOT NULL ," + // 3: thickness
                "\"SIGNAL_MIN\" REAL NOT NULL ," + // 4: signalMin
                "\"SIGNAL_MAX\" REAL NOT NULL );"); // 5: signalMax
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CURVE_MIN_MAX_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CurveMinMaxBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
        stmt.bindDouble(4, entity.getThickness());
        stmt.bindDouble(5, entity.getSignalMin());
        stmt.bindDouble(6, entity.getSignalMax());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CurveMinMaxBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
        stmt.bindDouble(4, entity.getThickness());
        stmt.bindDouble(5, entity.getSignalMin());
        stmt.bindDouble(6, entity.getSignalMax());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CurveMinMaxBean readEntity(Cursor cursor, int offset) {
        CurveMinMaxBean entity = new CurveMinMaxBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uniqueKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // rebarDiameter
            cursor.getDouble(offset + 3), // thickness
            cursor.getDouble(offset + 4), // signalMin
            cursor.getDouble(offset + 5) // signalMax
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CurveMinMaxBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUniqueKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRebarDiameter(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setThickness(cursor.getDouble(offset + 3));
        entity.setSignalMin(cursor.getDouble(offset + 4));
        entity.setSignalMax(cursor.getDouble(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CurveMinMaxBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CurveMinMaxBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CurveMinMaxBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
