package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.gtj_f230_rebound_corrosion.base.model.ProjectBean;
import com.example.gtj_f230_rebound_corrosion.base.model.ZoneBean;
import com.example.gtj_f230_rebound_corrosion.corrosion.model.CurveMinMaxBean;
import com.example.gtj_f230_rebound_corrosion.corrosion.model.MinMaxBean1;
import com.example.gtj_f230_rebound_corrosion.corrosion.model.RebarMinMaxBean;
import com.example.gtj_f230_rebound_corrosion.corrosion.model.StandardCurveBean;
import com.example.gtj_f230_rebound_corrosion.f230.model.WidthZoneBean;
import com.example.gtj_f230_rebound_corrosion.thickness.model.ConfigBean;
import com.example.gtj_f230_rebound_corrosion.thickness.model.Rebar240ZoneBean;

import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.ProjectBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.ZoneBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.CurveMinMaxBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.MinMaxBean1Dao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.RebarMinMaxBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.StandardCurveBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.WidthZoneBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.ConfigBeanDao;
import com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db.Rebar240ZoneBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectBeanDaoConfig;
    private final DaoConfig zoneBeanDaoConfig;
    private final DaoConfig curveMinMaxBeanDaoConfig;
    private final DaoConfig minMaxBean1DaoConfig;
    private final DaoConfig rebarMinMaxBeanDaoConfig;
    private final DaoConfig standardCurveBeanDaoConfig;
    private final DaoConfig widthZoneBeanDaoConfig;
    private final DaoConfig configBeanDaoConfig;
    private final DaoConfig rebar240ZoneBeanDaoConfig;

    private final ProjectBeanDao projectBeanDao;
    private final ZoneBeanDao zoneBeanDao;
    private final CurveMinMaxBeanDao curveMinMaxBeanDao;
    private final MinMaxBean1Dao minMaxBean1Dao;
    private final RebarMinMaxBeanDao rebarMinMaxBeanDao;
    private final StandardCurveBeanDao standardCurveBeanDao;
    private final WidthZoneBeanDao widthZoneBeanDao;
    private final ConfigBeanDao configBeanDao;
    private final Rebar240ZoneBeanDao rebar240ZoneBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectBeanDaoConfig = daoConfigMap.get(ProjectBeanDao.class).clone();
        projectBeanDaoConfig.initIdentityScope(type);

        zoneBeanDaoConfig = daoConfigMap.get(ZoneBeanDao.class).clone();
        zoneBeanDaoConfig.initIdentityScope(type);

        curveMinMaxBeanDaoConfig = daoConfigMap.get(CurveMinMaxBeanDao.class).clone();
        curveMinMaxBeanDaoConfig.initIdentityScope(type);

        minMaxBean1DaoConfig = daoConfigMap.get(MinMaxBean1Dao.class).clone();
        minMaxBean1DaoConfig.initIdentityScope(type);

        rebarMinMaxBeanDaoConfig = daoConfigMap.get(RebarMinMaxBeanDao.class).clone();
        rebarMinMaxBeanDaoConfig.initIdentityScope(type);

        standardCurveBeanDaoConfig = daoConfigMap.get(StandardCurveBeanDao.class).clone();
        standardCurveBeanDaoConfig.initIdentityScope(type);

        widthZoneBeanDaoConfig = daoConfigMap.get(WidthZoneBeanDao.class).clone();
        widthZoneBeanDaoConfig.initIdentityScope(type);

        configBeanDaoConfig = daoConfigMap.get(ConfigBeanDao.class).clone();
        configBeanDaoConfig.initIdentityScope(type);

        rebar240ZoneBeanDaoConfig = daoConfigMap.get(Rebar240ZoneBeanDao.class).clone();
        rebar240ZoneBeanDaoConfig.initIdentityScope(type);

        projectBeanDao = new ProjectBeanDao(projectBeanDaoConfig, this);
        zoneBeanDao = new ZoneBeanDao(zoneBeanDaoConfig, this);
        curveMinMaxBeanDao = new CurveMinMaxBeanDao(curveMinMaxBeanDaoConfig, this);
        minMaxBean1Dao = new MinMaxBean1Dao(minMaxBean1DaoConfig, this);
        rebarMinMaxBeanDao = new RebarMinMaxBeanDao(rebarMinMaxBeanDaoConfig, this);
        standardCurveBeanDao = new StandardCurveBeanDao(standardCurveBeanDaoConfig, this);
        widthZoneBeanDao = new WidthZoneBeanDao(widthZoneBeanDaoConfig, this);
        configBeanDao = new ConfigBeanDao(configBeanDaoConfig, this);
        rebar240ZoneBeanDao = new Rebar240ZoneBeanDao(rebar240ZoneBeanDaoConfig, this);

        registerDao(ProjectBean.class, projectBeanDao);
        registerDao(ZoneBean.class, zoneBeanDao);
        registerDao(CurveMinMaxBean.class, curveMinMaxBeanDao);
        registerDao(MinMaxBean1.class, minMaxBean1Dao);
        registerDao(RebarMinMaxBean.class, rebarMinMaxBeanDao);
        registerDao(StandardCurveBean.class, standardCurveBeanDao);
        registerDao(WidthZoneBean.class, widthZoneBeanDao);
        registerDao(ConfigBean.class, configBeanDao);
        registerDao(Rebar240ZoneBean.class, rebar240ZoneBeanDao);
    }
    
    public void clear() {
        projectBeanDaoConfig.clearIdentityScope();
        zoneBeanDaoConfig.clearIdentityScope();
        curveMinMaxBeanDaoConfig.clearIdentityScope();
        minMaxBean1DaoConfig.clearIdentityScope();
        rebarMinMaxBeanDaoConfig.clearIdentityScope();
        standardCurveBeanDaoConfig.clearIdentityScope();
        widthZoneBeanDaoConfig.clearIdentityScope();
        configBeanDaoConfig.clearIdentityScope();
        rebar240ZoneBeanDaoConfig.clearIdentityScope();
    }

    public ProjectBeanDao getProjectBeanDao() {
        return projectBeanDao;
    }

    public ZoneBeanDao getZoneBeanDao() {
        return zoneBeanDao;
    }

    public CurveMinMaxBeanDao getCurveMinMaxBeanDao() {
        return curveMinMaxBeanDao;
    }

    public MinMaxBean1Dao getMinMaxBean1Dao() {
        return minMaxBean1Dao;
    }

    public RebarMinMaxBeanDao getRebarMinMaxBeanDao() {
        return rebarMinMaxBeanDao;
    }

    public StandardCurveBeanDao getStandardCurveBeanDao() {
        return standardCurveBeanDao;
    }

    public WidthZoneBeanDao getWidthZoneBeanDao() {
        return widthZoneBeanDao;
    }

    public ConfigBeanDao getConfigBeanDao() {
        return configBeanDao;
    }

    public Rebar240ZoneBeanDao getRebar240ZoneBeanDao() {
        return rebar240ZoneBeanDao;
    }

}
