package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.corrosion.model.MinMaxBean1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MIN_MAX_BEAN1".
*/
public class MinMaxBean1Dao extends AbstractDao<MinMaxBean1, Long> {

    public static final String TABLENAME = "MIN_MAX_BEAN1";

    /**
     * Properties of entity MinMaxBean1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RebarDiameter = new Property(1, String.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property Thickness = new Property(2, int.class, "thickness", false, "THICKNESS");
        public final static Property Min = new Property(3, double.class, "min", false, "MIN");
        public final static Property Max = new Property(4, double.class, "max", false, "MAX");
    }


    public MinMaxBean1Dao(DaoConfig config) {
        super(config);
    }
    
    public MinMaxBean1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MIN_MAX_BEAN1\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REBAR_DIAMETER\" TEXT," + // 1: rebarDiameter
                "\"THICKNESS\" INTEGER NOT NULL ," + // 2: thickness
                "\"MIN\" REAL NOT NULL ," + // 3: min
                "\"MAX\" REAL NOT NULL );"); // 4: max
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MIN_MAX_BEAN1\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MinMaxBean1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(2, rebarDiameter);
        }
        stmt.bindLong(3, entity.getThickness());
        stmt.bindDouble(4, entity.getMin());
        stmt.bindDouble(5, entity.getMax());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MinMaxBean1 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(2, rebarDiameter);
        }
        stmt.bindLong(3, entity.getThickness());
        stmt.bindDouble(4, entity.getMin());
        stmt.bindDouble(5, entity.getMax());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MinMaxBean1 readEntity(Cursor cursor, int offset) {
        MinMaxBean1 entity = new MinMaxBean1( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rebarDiameter
            cursor.getInt(offset + 2), // thickness
            cursor.getDouble(offset + 3), // min
            cursor.getDouble(offset + 4) // max
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MinMaxBean1 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRebarDiameter(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThickness(cursor.getInt(offset + 2));
        entity.setMin(cursor.getDouble(offset + 3));
        entity.setMax(cursor.getDouble(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MinMaxBean1 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MinMaxBean1 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MinMaxBean1 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
