package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.base.storage.RebarBeanConverter;
import java.util.List;

import com.example.gtj_f230_rebound_corrosion.thickness.model.Rebar240ZoneBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REBAR240_ZONE_BEAN".
*/
public class Rebar240ZoneBeanDao extends AbstractDao<Rebar240ZoneBean, Long> {

    public static final String TABLENAME = "REBAR240_ZONE_BEAN";

    /**
     * Properties of entity Rebar240ZoneBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PoleNo = new Property(1, String.class, "poleNo", false, "POLE_NO");
        public final static Property PoleType = new Property(2, int.class, "poleType", false, "POLE_TYPE");
        public final static Property PoleStructure = new Property(3, int.class, "poleStructure", false, "POLE_STRUCTURE");
        public final static Property PoleStandard = new Property(4, int.class, "poleStandard", false, "POLE_STANDARD");
        public final static Property PoleHeight = new Property(5, String.class, "poleHeight", false, "POLE_HEIGHT");
        public final static Property PoleHeightReinforce = new Property(6, String.class, "poleHeightReinforce", false, "POLE_HEIGHT_REINFORCE");
        public final static Property PoleBottomDiameter = new Property(7, int.class, "poleBottomDiameter", false, "POLE_BOTTOM_DIAMETER");
        public final static Property PoleTopDiameter = new Property(8, int.class, "poleTopDiameter", false, "POLE_TOP_DIAMETER");
        public final static Property RebarDiameter = new Property(9, int.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property HoopingDiameter = new Property(10, int.class, "hoopingDiameter", false, "HOOPING_DIAMETER");
        public final static Property PoleBottomCount = new Property(11, int.class, "poleBottomCount", false, "POLE_BOTTOM_COUNT");
        public final static Property PoleTopCount = new Property(12, int.class, "poleTopCount", false, "POLE_TOP_COUNT");
        public final static Property DesignThickness = new Property(13, String.class, "designThickness", false, "DESIGN_THICKNESS");
        public final static Property RebarPageList = new Property(14, String.class, "rebarPageList", false, "REBAR_PAGE_LIST");
        public final static Property StartTime = new Property(15, String.class, "startTime", false, "START_TIME");
    }

    private final RebarBeanConverter rebarPageListConverter = new RebarBeanConverter();

    public Rebar240ZoneBeanDao(DaoConfig config) {
        super(config);
    }
    
    public Rebar240ZoneBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REBAR240_ZONE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"POLE_NO\" TEXT," + // 1: poleNo
                "\"POLE_TYPE\" INTEGER NOT NULL ," + // 2: poleType
                "\"POLE_STRUCTURE\" INTEGER NOT NULL ," + // 3: poleStructure
                "\"POLE_STANDARD\" INTEGER NOT NULL ," + // 4: poleStandard
                "\"POLE_HEIGHT\" TEXT," + // 5: poleHeight
                "\"POLE_HEIGHT_REINFORCE\" TEXT," + // 6: poleHeightReinforce
                "\"POLE_BOTTOM_DIAMETER\" INTEGER NOT NULL ," + // 7: poleBottomDiameter
                "\"POLE_TOP_DIAMETER\" INTEGER NOT NULL ," + // 8: poleTopDiameter
                "\"REBAR_DIAMETER\" INTEGER NOT NULL ," + // 9: rebarDiameter
                "\"HOOPING_DIAMETER\" INTEGER NOT NULL ," + // 10: hoopingDiameter
                "\"POLE_BOTTOM_COUNT\" INTEGER NOT NULL ," + // 11: poleBottomCount
                "\"POLE_TOP_COUNT\" INTEGER NOT NULL ," + // 12: poleTopCount
                "\"DESIGN_THICKNESS\" TEXT," + // 13: designThickness
                "\"REBAR_PAGE_LIST\" TEXT," + // 14: rebarPageList
                "\"START_TIME\" TEXT);"); // 15: startTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REBAR240_ZONE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Rebar240ZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poleNo = entity.getPoleNo();
        if (poleNo != null) {
            stmt.bindString(2, poleNo);
        }
        stmt.bindLong(3, entity.getPoleType());
        stmt.bindLong(4, entity.getPoleStructure());
        stmt.bindLong(5, entity.getPoleStandard());
 
        String poleHeight = entity.getPoleHeight();
        if (poleHeight != null) {
            stmt.bindString(6, poleHeight);
        }
 
        String poleHeightReinforce = entity.getPoleHeightReinforce();
        if (poleHeightReinforce != null) {
            stmt.bindString(7, poleHeightReinforce);
        }
        stmt.bindLong(8, entity.getPoleBottomDiameter());
        stmt.bindLong(9, entity.getPoleTopDiameter());
        stmt.bindLong(10, entity.getRebarDiameter());
        stmt.bindLong(11, entity.getHoopingDiameter());
        stmt.bindLong(12, entity.getPoleBottomCount());
        stmt.bindLong(13, entity.getPoleTopCount());
 
        String designThickness = entity.getDesignThickness();
        if (designThickness != null) {
            stmt.bindString(14, designThickness);
        }
 
        List rebarPageList = entity.getRebarPageList();
        if (rebarPageList != null) {
            stmt.bindString(15, rebarPageListConverter.convertToDatabaseValue(rebarPageList));
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(16, startTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Rebar240ZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String poleNo = entity.getPoleNo();
        if (poleNo != null) {
            stmt.bindString(2, poleNo);
        }
        stmt.bindLong(3, entity.getPoleType());
        stmt.bindLong(4, entity.getPoleStructure());
        stmt.bindLong(5, entity.getPoleStandard());
 
        String poleHeight = entity.getPoleHeight();
        if (poleHeight != null) {
            stmt.bindString(6, poleHeight);
        }
 
        String poleHeightReinforce = entity.getPoleHeightReinforce();
        if (poleHeightReinforce != null) {
            stmt.bindString(7, poleHeightReinforce);
        }
        stmt.bindLong(8, entity.getPoleBottomDiameter());
        stmt.bindLong(9, entity.getPoleTopDiameter());
        stmt.bindLong(10, entity.getRebarDiameter());
        stmt.bindLong(11, entity.getHoopingDiameter());
        stmt.bindLong(12, entity.getPoleBottomCount());
        stmt.bindLong(13, entity.getPoleTopCount());
 
        String designThickness = entity.getDesignThickness();
        if (designThickness != null) {
            stmt.bindString(14, designThickness);
        }
 
        List rebarPageList = entity.getRebarPageList();
        if (rebarPageList != null) {
            stmt.bindString(15, rebarPageListConverter.convertToDatabaseValue(rebarPageList));
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(16, startTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Rebar240ZoneBean readEntity(Cursor cursor, int offset) {
        Rebar240ZoneBean entity = new Rebar240ZoneBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // poleNo
            cursor.getInt(offset + 2), // poleType
            cursor.getInt(offset + 3), // poleStructure
            cursor.getInt(offset + 4), // poleStandard
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // poleHeight
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // poleHeightReinforce
            cursor.getInt(offset + 7), // poleBottomDiameter
            cursor.getInt(offset + 8), // poleTopDiameter
            cursor.getInt(offset + 9), // rebarDiameter
            cursor.getInt(offset + 10), // hoopingDiameter
            cursor.getInt(offset + 11), // poleBottomCount
            cursor.getInt(offset + 12), // poleTopCount
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // designThickness
            cursor.isNull(offset + 14) ? null : rebarPageListConverter.convertToEntityProperty(cursor.getString(offset + 14)), // rebarPageList
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // startTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Rebar240ZoneBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPoleNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPoleType(cursor.getInt(offset + 2));
        entity.setPoleStructure(cursor.getInt(offset + 3));
        entity.setPoleStandard(cursor.getInt(offset + 4));
        entity.setPoleHeight(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPoleHeightReinforce(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPoleBottomDiameter(cursor.getInt(offset + 7));
        entity.setPoleTopDiameter(cursor.getInt(offset + 8));
        entity.setRebarDiameter(cursor.getInt(offset + 9));
        entity.setHoopingDiameter(cursor.getInt(offset + 10));
        entity.setPoleBottomCount(cursor.getInt(offset + 11));
        entity.setPoleTopCount(cursor.getInt(offset + 12));
        entity.setDesignThickness(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setRebarPageList(cursor.isNull(offset + 14) ? null : rebarPageListConverter.convertToEntityProperty(cursor.getString(offset + 14)));
        entity.setStartTime(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Rebar240ZoneBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Rebar240ZoneBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Rebar240ZoneBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
