package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.corrosion.storage.CurveDoubleConverter;

import com.example.gtj_f230_rebound_corrosion.corrosion.model.RebarMinMaxBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REBAR_MIN_MAX_BEAN".
*/
public class RebarMinMaxBeanDao extends AbstractDao<RebarMinMaxBean, Long> {

    public static final String TABLENAME = "REBAR_MIN_MAX_BEAN";

    /**
     * Properties of entity RebarMinMaxBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UniqueKey = new Property(1, String.class, "uniqueKey", false, "UNIQUE_KEY");
        public final static Property RebarDiameter = new Property(2, String.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property PoleDiameter = new Property(3, String.class, "poleDiameter", false, "POLE_DIAMETER");
        public final static Property RebarSpacingMin = new Property(4, String.class, "rebarSpacingMin", false, "REBAR_SPACING_MIN");
        public final static Property RebarSpacingMax = new Property(5, String.class, "rebarSpacingMax", false, "REBAR_SPACING_MAX");
        public final static Property SpiralSpacing = new Property(6, String.class, "spiralSpacing", false, "SPIRAL_SPACING");
        public final static Property SignalMin = new Property(7, String.class, "signalMin", false, "SIGNAL_MIN");
        public final static Property SignalMax = new Property(8, String.class, "signalMax", false, "SIGNAL_MAX");
    }

    private final CurveDoubleConverter signalMinConverter = new CurveDoubleConverter();
    private final CurveDoubleConverter signalMaxConverter = new CurveDoubleConverter();

    public RebarMinMaxBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RebarMinMaxBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REBAR_MIN_MAX_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UNIQUE_KEY\" TEXT UNIQUE ," + // 1: uniqueKey
                "\"REBAR_DIAMETER\" TEXT," + // 2: rebarDiameter
                "\"POLE_DIAMETER\" TEXT," + // 3: poleDiameter
                "\"REBAR_SPACING_MIN\" TEXT," + // 4: rebarSpacingMin
                "\"REBAR_SPACING_MAX\" TEXT," + // 5: rebarSpacingMax
                "\"SPIRAL_SPACING\" TEXT," + // 6: spiralSpacing
                "\"SIGNAL_MIN\" TEXT," + // 7: signalMin
                "\"SIGNAL_MAX\" TEXT);"); // 8: signalMax
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REBAR_MIN_MAX_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RebarMinMaxBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
 
        String poleDiameter = entity.getPoleDiameter();
        if (poleDiameter != null) {
            stmt.bindString(4, poleDiameter);
        }
 
        String rebarSpacingMin = entity.getRebarSpacingMin();
        if (rebarSpacingMin != null) {
            stmt.bindString(5, rebarSpacingMin);
        }
 
        String rebarSpacingMax = entity.getRebarSpacingMax();
        if (rebarSpacingMax != null) {
            stmt.bindString(6, rebarSpacingMax);
        }
 
        String spiralSpacing = entity.getSpiralSpacing();
        if (spiralSpacing != null) {
            stmt.bindString(7, spiralSpacing);
        }
 
        double[] signalMin = entity.getSignalMin();
        if (signalMin != null) {
            stmt.bindString(8, signalMinConverter.convertToDatabaseValue(signalMin));
        }
 
        double[] signalMax = entity.getSignalMax();
        if (signalMax != null) {
            stmt.bindString(9, signalMaxConverter.convertToDatabaseValue(signalMax));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RebarMinMaxBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
 
        String poleDiameter = entity.getPoleDiameter();
        if (poleDiameter != null) {
            stmt.bindString(4, poleDiameter);
        }
 
        String rebarSpacingMin = entity.getRebarSpacingMin();
        if (rebarSpacingMin != null) {
            stmt.bindString(5, rebarSpacingMin);
        }
 
        String rebarSpacingMax = entity.getRebarSpacingMax();
        if (rebarSpacingMax != null) {
            stmt.bindString(6, rebarSpacingMax);
        }
 
        String spiralSpacing = entity.getSpiralSpacing();
        if (spiralSpacing != null) {
            stmt.bindString(7, spiralSpacing);
        }
 
        double[] signalMin = entity.getSignalMin();
        if (signalMin != null) {
            stmt.bindString(8, signalMinConverter.convertToDatabaseValue(signalMin));
        }
 
        double[] signalMax = entity.getSignalMax();
        if (signalMax != null) {
            stmt.bindString(9, signalMaxConverter.convertToDatabaseValue(signalMax));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RebarMinMaxBean readEntity(Cursor cursor, int offset) {
        RebarMinMaxBean entity = new RebarMinMaxBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uniqueKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // rebarDiameter
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // poleDiameter
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // rebarSpacingMin
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // rebarSpacingMax
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // spiralSpacing
            cursor.isNull(offset + 7) ? null : signalMinConverter.convertToEntityProperty(cursor.getString(offset + 7)), // signalMin
            cursor.isNull(offset + 8) ? null : signalMaxConverter.convertToEntityProperty(cursor.getString(offset + 8)) // signalMax
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RebarMinMaxBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUniqueKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRebarDiameter(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPoleDiameter(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRebarSpacingMin(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRebarSpacingMax(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSpiralSpacing(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSignalMin(cursor.isNull(offset + 7) ? null : signalMinConverter.convertToEntityProperty(cursor.getString(offset + 7)));
        entity.setSignalMax(cursor.isNull(offset + 8) ? null : signalMaxConverter.convertToEntityProperty(cursor.getString(offset + 8)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RebarMinMaxBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RebarMinMaxBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RebarMinMaxBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
