package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.corrosion.storage.CurveDoubleConverter;

import com.example.gtj_f230_rebound_corrosion.corrosion.model.StandardCurveBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STANDARD_CURVE_BEAN".
*/
public class StandardCurveBeanDao extends AbstractDao<StandardCurveBean, Long> {

    public static final String TABLENAME = "STANDARD_CURVE_BEAN";

    /**
     * Properties of entity StandardCurveBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UniqueKey = new Property(1, String.class, "uniqueKey", false, "UNIQUE_KEY");
        public final static Property RebarDiameter = new Property(2, String.class, "rebarDiameter", false, "REBAR_DIAMETER");
        public final static Property PoleDiameter = new Property(3, String.class, "poleDiameter", false, "POLE_DIAMETER");
        public final static Property RebarSpacing = new Property(4, String.class, "rebarSpacing", false, "REBAR_SPACING");
        public final static Property SpiralSpacing = new Property(5, String.class, "spiralSpacing", false, "SPIRAL_SPACING");
        public final static Property Thickness = new Property(6, double.class, "thickness", false, "THICKNESS");
        public final static Property SignalArray = new Property(7, String.class, "signalArray", false, "SIGNAL_ARRAY");
        public final static Property SignalProcessed = new Property(8, String.class, "signalProcessed", false, "SIGNAL_PROCESSED");
        public final static Property SignalMovAve = new Property(9, String.class, "signalMovAve", false, "SIGNAL_MOV_AVE");
    }

    private final CurveDoubleConverter signalArrayConverter = new CurveDoubleConverter();
    private final CurveDoubleConverter signalProcessedConverter = new CurveDoubleConverter();
    private final CurveDoubleConverter signalMovAveConverter = new CurveDoubleConverter();

    public StandardCurveBeanDao(DaoConfig config) {
        super(config);
    }
    
    public StandardCurveBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STANDARD_CURVE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UNIQUE_KEY\" TEXT UNIQUE ," + // 1: uniqueKey
                "\"REBAR_DIAMETER\" TEXT," + // 2: rebarDiameter
                "\"POLE_DIAMETER\" TEXT," + // 3: poleDiameter
                "\"REBAR_SPACING\" TEXT," + // 4: rebarSpacing
                "\"SPIRAL_SPACING\" TEXT," + // 5: spiralSpacing
                "\"THICKNESS\" REAL NOT NULL ," + // 6: thickness
                "\"SIGNAL_ARRAY\" TEXT," + // 7: signalArray
                "\"SIGNAL_PROCESSED\" TEXT," + // 8: signalProcessed
                "\"SIGNAL_MOV_AVE\" TEXT);"); // 9: signalMovAve
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STANDARD_CURVE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StandardCurveBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
 
        String poleDiameter = entity.getPoleDiameter();
        if (poleDiameter != null) {
            stmt.bindString(4, poleDiameter);
        }
 
        String rebarSpacing = entity.getRebarSpacing();
        if (rebarSpacing != null) {
            stmt.bindString(5, rebarSpacing);
        }
 
        String spiralSpacing = entity.getSpiralSpacing();
        if (spiralSpacing != null) {
            stmt.bindString(6, spiralSpacing);
        }
        stmt.bindDouble(7, entity.getThickness());
 
        double[] signalArray = entity.getSignalArray();
        if (signalArray != null) {
            stmt.bindString(8, signalArrayConverter.convertToDatabaseValue(signalArray));
        }
 
        double[] signalProcessed = entity.getSignalProcessed();
        if (signalProcessed != null) {
            stmt.bindString(9, signalProcessedConverter.convertToDatabaseValue(signalProcessed));
        }
 
        double[] signalMovAve = entity.getSignalMovAve();
        if (signalMovAve != null) {
            stmt.bindString(10, signalMovAveConverter.convertToDatabaseValue(signalMovAve));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StandardCurveBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String uniqueKey = entity.getUniqueKey();
        if (uniqueKey != null) {
            stmt.bindString(2, uniqueKey);
        }
 
        String rebarDiameter = entity.getRebarDiameter();
        if (rebarDiameter != null) {
            stmt.bindString(3, rebarDiameter);
        }
 
        String poleDiameter = entity.getPoleDiameter();
        if (poleDiameter != null) {
            stmt.bindString(4, poleDiameter);
        }
 
        String rebarSpacing = entity.getRebarSpacing();
        if (rebarSpacing != null) {
            stmt.bindString(5, rebarSpacing);
        }
 
        String spiralSpacing = entity.getSpiralSpacing();
        if (spiralSpacing != null) {
            stmt.bindString(6, spiralSpacing);
        }
        stmt.bindDouble(7, entity.getThickness());
 
        double[] signalArray = entity.getSignalArray();
        if (signalArray != null) {
            stmt.bindString(8, signalArrayConverter.convertToDatabaseValue(signalArray));
        }
 
        double[] signalProcessed = entity.getSignalProcessed();
        if (signalProcessed != null) {
            stmt.bindString(9, signalProcessedConverter.convertToDatabaseValue(signalProcessed));
        }
 
        double[] signalMovAve = entity.getSignalMovAve();
        if (signalMovAve != null) {
            stmt.bindString(10, signalMovAveConverter.convertToDatabaseValue(signalMovAve));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StandardCurveBean readEntity(Cursor cursor, int offset) {
        StandardCurveBean entity = new StandardCurveBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // uniqueKey
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // rebarDiameter
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // poleDiameter
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // rebarSpacing
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // spiralSpacing
            cursor.getDouble(offset + 6), // thickness
            cursor.isNull(offset + 7) ? null : signalArrayConverter.convertToEntityProperty(cursor.getString(offset + 7)), // signalArray
            cursor.isNull(offset + 8) ? null : signalProcessedConverter.convertToEntityProperty(cursor.getString(offset + 8)), // signalProcessed
            cursor.isNull(offset + 9) ? null : signalMovAveConverter.convertToEntityProperty(cursor.getString(offset + 9)) // signalMovAve
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StandardCurveBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUniqueKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRebarDiameter(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPoleDiameter(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRebarSpacing(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSpiralSpacing(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setThickness(cursor.getDouble(offset + 6));
        entity.setSignalArray(cursor.isNull(offset + 7) ? null : signalArrayConverter.convertToEntityProperty(cursor.getString(offset + 7)));
        entity.setSignalProcessed(cursor.isNull(offset + 8) ? null : signalProcessedConverter.convertToEntityProperty(cursor.getString(offset + 8)));
        entity.setSignalMovAve(cursor.isNull(offset + 9) ? null : signalMovAveConverter.convertToEntityProperty(cursor.getString(offset + 9)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StandardCurveBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StandardCurveBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StandardCurveBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
