package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.f230.model.WidthZoneBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WIDTH_ZONE_BEAN".
*/
public class WidthZoneBeanDao extends AbstractDao<WidthZoneBean, Long> {

    public static final String TABLENAME = "WIDTH_ZONE_BEAN";

    /**
     * Properties of entity WidthZoneBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Num = new Property(1, String.class, "num", false, "NUM");
        public final static Property StrZoneList = new Property(2, String.class, "strZoneList", false, "STR_ZONE_LIST");
        public final static Property ZoneListCount = new Property(3, int.class, "zoneListCount", false, "ZONE_LIST_COUNT");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property Address = new Property(5, String.class, "address", false, "ADDRESS");
        public final static Property Inspector = new Property(6, String.class, "inspector", false, "INSPECTOR");
        public final static Property ImageList = new Property(7, String.class, "imageList", false, "IMAGE_LIST");
        public final static Property StartTime = new Property(8, String.class, "startTime", false, "START_TIME");
        public final static Property Lontitude = new Property(9, double.class, "lontitude", false, "LONTITUDE");
        public final static Property Latitude = new Property(10, double.class, "latitude", false, "LATITUDE");
        public final static Property Altitude = new Property(11, double.class, "altitude", false, "ALTITUDE");
        public final static Property Upload = new Property(12, int.class, "upload", false, "UPLOAD");
    }


    public WidthZoneBeanDao(DaoConfig config) {
        super(config);
    }
    
    public WidthZoneBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WIDTH_ZONE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"NUM\" TEXT," + // 1: num
                "\"STR_ZONE_LIST\" TEXT," + // 2: strZoneList
                "\"ZONE_LIST_COUNT\" INTEGER NOT NULL ," + // 3: zoneListCount
                "\"REMARK\" TEXT," + // 4: remark
                "\"ADDRESS\" TEXT," + // 5: address
                "\"INSPECTOR\" TEXT," + // 6: inspector
                "\"IMAGE_LIST\" TEXT," + // 7: imageList
                "\"START_TIME\" TEXT," + // 8: startTime
                "\"LONTITUDE\" REAL NOT NULL ," + // 9: lontitude
                "\"LATITUDE\" REAL NOT NULL ," + // 10: latitude
                "\"ALTITUDE\" REAL NOT NULL ," + // 11: altitude
                "\"UPLOAD\" INTEGER NOT NULL );"); // 12: upload
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WIDTH_ZONE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WidthZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(2, num);
        }
 
        String strZoneList = entity.getStrZoneList();
        if (strZoneList != null) {
            stmt.bindString(3, strZoneList);
        }
        stmt.bindLong(4, entity.getZoneListCount());
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(6, address);
        }
 
        String inspector = entity.getInspector();
        if (inspector != null) {
            stmt.bindString(7, inspector);
        }
 
        String imageList = entity.getImageList();
        if (imageList != null) {
            stmt.bindString(8, imageList);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(9, startTime);
        }
        stmt.bindDouble(10, entity.getLontitude());
        stmt.bindDouble(11, entity.getLatitude());
        stmt.bindDouble(12, entity.getAltitude());
        stmt.bindLong(13, entity.getUpload());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WidthZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String num = entity.getNum();
        if (num != null) {
            stmt.bindString(2, num);
        }
 
        String strZoneList = entity.getStrZoneList();
        if (strZoneList != null) {
            stmt.bindString(3, strZoneList);
        }
        stmt.bindLong(4, entity.getZoneListCount());
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(6, address);
        }
 
        String inspector = entity.getInspector();
        if (inspector != null) {
            stmt.bindString(7, inspector);
        }
 
        String imageList = entity.getImageList();
        if (imageList != null) {
            stmt.bindString(8, imageList);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(9, startTime);
        }
        stmt.bindDouble(10, entity.getLontitude());
        stmt.bindDouble(11, entity.getLatitude());
        stmt.bindDouble(12, entity.getAltitude());
        stmt.bindLong(13, entity.getUpload());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WidthZoneBean readEntity(Cursor cursor, int offset) {
        WidthZoneBean entity = new WidthZoneBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // num
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // strZoneList
            cursor.getInt(offset + 3), // zoneListCount
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // address
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // inspector
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // imageList
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // startTime
            cursor.getDouble(offset + 9), // lontitude
            cursor.getDouble(offset + 10), // latitude
            cursor.getDouble(offset + 11), // altitude
            cursor.getInt(offset + 12) // upload
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WidthZoneBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNum(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStrZoneList(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setZoneListCount(cursor.getInt(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddress(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setInspector(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImageList(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStartTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLontitude(cursor.getDouble(offset + 9));
        entity.setLatitude(cursor.getDouble(offset + 10));
        entity.setAltitude(cursor.getDouble(offset + 11));
        entity.setUpload(cursor.getInt(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WidthZoneBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WidthZoneBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WidthZoneBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
