package com.example.gtj_f230_rebound_corrosion.functions.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.gtj_f230_rebound_corrosion.base.model.CorrosionZoneBean;
import com.example.gtj_f230_rebound_corrosion.base.model.F230ZoneBean;
import com.example.gtj_f230_rebound_corrosion.base.model.RebounderZoneBean;
import com.example.gtj_f230_rebound_corrosion.base.storage.CorrosionZoneBeanConverter;
import com.example.gtj_f230_rebound_corrosion.base.storage.F230ZoneBeanConverter;
import com.example.gtj_f230_rebound_corrosion.base.storage.ReboundZoneBeanConverter;

import com.example.gtj_f230_rebound_corrosion.base.model.ZoneBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZONE_BEAN".
*/
public class ZoneBeanDao extends AbstractDao<ZoneBean, Long> {

    public static final String TABLENAME = "ZONE_BEAN";

    /**
     * Properties of entity ZoneBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ProjectId = new Property(1, long.class, "projectId", false, "PROJECT_ID");
        public final static Property ProjectName = new Property(2, String.class, "projectName", false, "PROJECT_NAME");
        public final static Property Number = new Property(3, String.class, "number", false, "NUMBER");
        public final static Property Remark = new Property(4, String.class, "remark", false, "REMARK");
        public final static Property F230ZoneBean = new Property(5, String.class, "f230ZoneBean", false, "F230_ZONE_BEAN");
        public final static Property RebounderZoneBean = new Property(6, String.class, "rebounderZoneBean", false, "REBOUNDER_ZONE_BEAN");
        public final static Property CorrosionZoneBean = new Property(7, String.class, "corrosionZoneBean", false, "CORROSION_ZONE_BEAN");
        public final static Property ThicknessId = new Property(8, long.class, "thicknessId", false, "THICKNESS_ID");
        public final static Property ThicknessCount = new Property(9, int.class, "thicknessCount", false, "THICKNESS_COUNT");
    }

    private final F230ZoneBeanConverter f230ZoneBeanConverter = new F230ZoneBeanConverter();
    private final ReboundZoneBeanConverter rebounderZoneBeanConverter = new ReboundZoneBeanConverter();
    private final CorrosionZoneBeanConverter corrosionZoneBeanConverter = new CorrosionZoneBeanConverter();

    public ZoneBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ZoneBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZONE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PROJECT_ID\" INTEGER NOT NULL ," + // 1: projectId
                "\"PROJECT_NAME\" TEXT," + // 2: projectName
                "\"NUMBER\" TEXT," + // 3: number
                "\"REMARK\" TEXT," + // 4: remark
                "\"F230_ZONE_BEAN\" TEXT," + // 5: f230ZoneBean
                "\"REBOUNDER_ZONE_BEAN\" TEXT," + // 6: rebounderZoneBean
                "\"CORROSION_ZONE_BEAN\" TEXT," + // 7: corrosionZoneBean
                "\"THICKNESS_ID\" INTEGER NOT NULL ," + // 8: thicknessId
                "\"THICKNESS_COUNT\" INTEGER NOT NULL );"); // 9: thicknessCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZONE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getProjectId());
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(3, projectName);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(4, number);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        F230ZoneBean f230ZoneBean = entity.getF230ZoneBean();
        if (f230ZoneBean != null) {
            stmt.bindString(6, f230ZoneBeanConverter.convertToDatabaseValue(f230ZoneBean));
        }
 
        RebounderZoneBean rebounderZoneBean = entity.getRebounderZoneBean();
        if (rebounderZoneBean != null) {
            stmt.bindString(7, rebounderZoneBeanConverter.convertToDatabaseValue(rebounderZoneBean));
        }
 
        CorrosionZoneBean corrosionZoneBean = entity.getCorrosionZoneBean();
        if (corrosionZoneBean != null) {
            stmt.bindString(8, corrosionZoneBeanConverter.convertToDatabaseValue(corrosionZoneBean));
        }
        stmt.bindLong(9, entity.getThicknessId());
        stmt.bindLong(10, entity.getThicknessCount());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZoneBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getProjectId());
 
        String projectName = entity.getProjectName();
        if (projectName != null) {
            stmt.bindString(3, projectName);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(4, number);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(5, remark);
        }
 
        F230ZoneBean f230ZoneBean = entity.getF230ZoneBean();
        if (f230ZoneBean != null) {
            stmt.bindString(6, f230ZoneBeanConverter.convertToDatabaseValue(f230ZoneBean));
        }
 
        RebounderZoneBean rebounderZoneBean = entity.getRebounderZoneBean();
        if (rebounderZoneBean != null) {
            stmt.bindString(7, rebounderZoneBeanConverter.convertToDatabaseValue(rebounderZoneBean));
        }
 
        CorrosionZoneBean corrosionZoneBean = entity.getCorrosionZoneBean();
        if (corrosionZoneBean != null) {
            stmt.bindString(8, corrosionZoneBeanConverter.convertToDatabaseValue(corrosionZoneBean));
        }
        stmt.bindLong(9, entity.getThicknessId());
        stmt.bindLong(10, entity.getThicknessCount());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ZoneBean readEntity(Cursor cursor, int offset) {
        ZoneBean entity = new ZoneBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // projectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // projectName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // number
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // remark
            cursor.isNull(offset + 5) ? null : f230ZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 5)), // f230ZoneBean
            cursor.isNull(offset + 6) ? null : rebounderZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 6)), // rebounderZoneBean
            cursor.isNull(offset + 7) ? null : corrosionZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 7)), // corrosionZoneBean
            cursor.getLong(offset + 8), // thicknessId
            cursor.getInt(offset + 9) // thicknessCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZoneBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProjectId(cursor.getLong(offset + 1));
        entity.setProjectName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRemark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setF230ZoneBean(cursor.isNull(offset + 5) ? null : f230ZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 5)));
        entity.setRebounderZoneBean(cursor.isNull(offset + 6) ? null : rebounderZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 6)));
        entity.setCorrosionZoneBean(cursor.isNull(offset + 7) ? null : corrosionZoneBeanConverter.convertToEntityProperty(cursor.getString(offset + 7)));
        entity.setThicknessId(cursor.getLong(offset + 8));
        entity.setThicknessCount(cursor.getInt(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZoneBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ZoneBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZoneBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
